server:
  port: 80

spring:
  application:
    name: cloud-order-service
eureka:
  client:
    #表示是否将自己注册进eurekaserver 默认为true
    register-with-eureka: false
    # 是否从eurekaserver抓取已有的注册信息 默认为true 单点无所谓，集群必须设置为true 才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版
#设置feign客户端超时时间
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  # 知道feign以什么级别监控哪个接口
  level:
    com.order.service.PaymentFeignService: debug
